export const HOMEPAGECARDS_LOADING = 'HOMEPAGECARDS_LOADING';
export const HOMEPAGECARDS_FAILED = 'HOMEPAGECARDS_FAILED';
export const ADD_HOMEPAGECARDS = 'ADD_HOMEPAGECARDS';
export const HOMEPAGECAROUSEL_LOADING = 'HOMEPAGECAROUSEL_LOADING';
export const HOMEPAGECAROUSEL_FAILED = 'HOMEPAGECAROUSEL_FAILED';
export const ADD_HOMEPAGECAROUSELPAGE = 'ADD_HOMEPAGECAROUSELPAGE';

export const WHYIDPAGE_LOADING = 'WHYIDPAGE_LOADING';
export const WHYIDPAGE_FAILED = 'WHYIDPAGE_FAILED';
export const ADD_WHYIDPAGE = 'ADD_WHYIDPAGE';

export const ONLINEPAGE_LOADING = 'ONLINEPAGE_LOADING';
export const ONLINEPAGE_FAILED = 'ONLINEPAGE_FAILED';
export const ADD_ONLINEPAGE = 'ADD_ONLINEPAGE';
export const ONLINEPAGECARDS_LOADING = 'ONLINEPAGECARDS_LOADING';
export const ONLINEPAGECARDS_FAILED = 'ONLINEPAGECARDS_FAILED';
export const ADD_ONLINEPAGECARDS = 'ADD_ONLINEPAGECARDS';

export const VIRTUALPAGE_LOADING = 'VIRTUALPAGE_LOADING';
export const VIRTUALPAGE_FAILED = 'VIRTUALPAGE_FAILED';
export const ADD_VIRTUALPAGE = 'ADD_VIRTUALPAGE'

export const LEARNINGPAGE_LOADING = 'LEARNINGPAGE_LOADING';
export const LEARNINGPAGE_FAILED = 'LEARNINGPAGE_FAILED';
export const ADD_LEARNINGPAGE = 'ADD_LEARNINGPAGE';

export const COURSESPAGE_LOADING = 'COURSESPAGE_LOADING';
export const COURSESPAGE_FAILED = 'COURSESPAGE_FAILED';
export const ADD_COURSESPAGE = 'ADD_COURSESPAGE';
export const COURSESPAGESIDEBAR_LOADING = 'COURSESPAGESIDEBAR_LOADING';
export const COURSESPAGESIDEBAR_FAILED = 'COURSESPAGESIDEBAR_FAILED';
export const ADD_COURSESPAGESIDEBAR = 'ADD_COURSESPAGESIDEBAR';
export const COURSESPAGESEARCHRESULTS_LOADING = 'COURSESPAGESEARCHRESULTS_LOADING';
export const COURSESPAGESEARCHRESULTS_FAILED = 'COURSESPAGESEARCHRESULTS_FAILED';
export const ADD_COURSESPAGESEARCHRESULTS = 'ADD_COURSESPAGESEARCHRESULTS';

export const REGISTERPAGE_LOADING = 'REGISTERPAGE_LOADING';
export const REGISTERPAGE_FAILED = 'REGISTERPAGE_FAILED';
export const ADD_REGISTERPAGE = 'ADD_REGISTERPAGE';